apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call props wf
on:
  workflow_dispatch:
jobs:
  call_rwf:
    uses: gmaxey/subworkflows/.cloudbees/workflows/use-properties.yaml
    secrets:
      sec: ${{ secrets.sec }}
