apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call props wf
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: echo org property
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo ${{ vars.prop }}
          echo ${{ secrets.sec }}

