apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy Subworkflow
on:
  workflow_call:
    inputs:
      artifactName:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
jobs:
  deploy:
    steps:
      - name: Inform system that an artifact version was deployed
        uses: cloudbees-io/register-deployed-artifact@greg_env_playground
        with:
          name: "${{ inputs.artifactName }}"
          version: "${{ inputs.artifactVersion }}"
          url: "docker.io/MyApp/${{ inputs.artifactName }}:${{ inputs.artifactVersion }}"
