apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: On-demand deploy to user-specified environment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: QA
        required: true
        description: Where to deploy the artifact version
      artifactName:
        type: string
        required: true
        default: Subworkflow
      artifactVersion:
        type: string
        required: true
        default: 1.0.0-0.0.18
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    steps:
      - name: Run component deployment
        uses: ./deploy.yaml
        with:
          artifactName: ${{ inputs.artifactName }}
          artifactVersion: ${{ inputs.artifactVersion }}
